/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DataCloud {
    'data': any[];
  }
  interface MyComponent {
    /**
    * The first name
    */
    'data': any;
    'myTitle': string;
    'printConsoleLog': () => Promise<void>;
  }
}

declare global {


  interface HTMLDataCloudElement extends Components.DataCloud, HTMLStencilElement {}
  var HTMLDataCloudElement: {
    prototype: HTMLDataCloudElement;
    new (): HTMLDataCloudElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'data-cloud': HTMLDataCloudElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface DataCloud {
    'data'?: any[];
  }
  interface MyComponent {
    /**
    * The first name
    */
    'data'?: any;
    'myTitle'?: string;
  }

  interface IntrinsicElements {
    'data-cloud': DataCloud;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'data-cloud': LocalJSX.DataCloud & JSXBase.HTMLAttributes<HTMLDataCloudElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


